"""Create user model migrations.

Revision ID: 423787ae91b1
Revises: 0a620926119e
Create Date: 2021-03-19 18:26:15.323996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423787ae91b1'
down_revision = '0a620926119e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
